# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_735_702_400 # January 1, 2025 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "paris"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.28"
  src = "src"
  test = "test"

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  celo = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api", chain = 42220 }
  celo-sepolia = { key = "${CELOSCAN_API_KEY}", url = "https://celo-sepolia.blockscout.com/api", chain = 11142220 }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  celo = "https://forno.celo.org"
  celo-sepolia = "https://forno.celo-sepolia.celo-testnet.org"
  localhost = "http://localhost:8545"